### ISSUE TITLE
@pulumi/newrelic: NEWRELIC_API_KEY is not being transmitted when set as an environment variable

### ISSUE THREAD

**Issue by HansMoleman** [pulumi/pulumi-newrelic#1]
On my local machine, I set NEWRELIC_API_KEY as an environment variable to a known working NewRelic key. My index.ts just has

```ts
import * as newrelic from "@pulumi/newrelic"

export const fooAlertChannel = pulumi.output(newrelic.getAlertChannel({
         name: "bngo"
}));
```

Once I do `pulumi up`, I get the following error:
`
Error: invocation of newrelic:index/getAlertChannel:getAlertChannel returned an error: invoking newrelic:index/getAlertChannel:getAlertChannel: The API key provided is invalid
`

**Comment by HansMoleman** [comment]
`const nrprovider = new newrelic.Provider("somename", {
  apiKey: "whatever"
});`

In the sample code above, any value that I set for apiKey is not being transmitted. Regardless of what I pass in, Pulumi will attempt to grab the `newrelic:apiKey` from `pulumi config`.

**Comment by HansMoleman** [comment]
Hello - any updates on this ticket? Thanks!

**Comment by HansMoleman** [comment]
This issue still isn't resolved. Can we re-open this bug?

**Comment by lukehoban** [comment]
Just for cross-linking - adding that this was re-opened at: https://github.com/pulumi/pulumi-newrelic/issues/7.
