### ISSUE TITLE
Unable to reference AlertPolicyChannel.id (and other id attributes)

### ISSUE THREAD

**Issue by iambrianngo** [pulumi/pulumi-newrelic#10]
The example provided in the code throws an error around `fooAlertChannel.id` and `fooAlertPolicy.id`. Here's the sample code provided

```
const fooAlertChannel = new newrelic.AlertChannel("foo", {
        configuration: {
            include_json_attachment: "1",
            recipients: "foo@example.com",
        },
        type: "email",
    });
const fooAlertPolicy = new newrelic.AlertPolicy("foo", {});
const fooAlertPolicyChannel = new newrelic.AlertPolicyChannel("foo", {
    channelId: fooAlertChannel.id,
    policyId: fooAlertPolicy.id,
});
```

Here's the error
```
Type 'Output<string>' is not assignable to type 'Input<number>'.
  Type 'Output<string>' is not assignable to type 'OutputInstance<number>'.
```

**Comment by stack72** [comment]
Circling back on this one - there is a bug in our pulumi-terraform library that we need to look at. But the workaround for this, in the meantime, is:

```
const fooAlertPolicyChannel = new newrelic.AlertPolicyChannel("foo", {
    channelId: fooAlertChannel.id.apply(id => parseInt(id)),
    policyId: fooAlertPolicy.id.apply(id => parseInt(id)),
});
```

**Comment by austinbutler** [comment]
This bit me today and it's had to debug, all you get back is `maximum retries reached: A downstream error occurred., [{"extensions":{"code":"INTERNAL_SERVER_ERROR"},"message":"Unknown Error"}]`.

@stack72 any ETA on this getting resolved?

**Comment by tleung999** [comment]
Hi there.  This also bit me for a good part of the day until I found this post.   Can we either have the doc examples reflect the temporary workaround or actually get this fixed?
