### ISSUE TITLE
Incorrect type hint for NrqlAlertCondition valueFunction

### ISSUE THREAD

**Issue by austinbutler** [pulumi/pulumi-newrelic#196]
With TypeScript, when creating a `NrqlAlertCondition`, it suggests `singleValue` as an option for `valueFunction`, but when running `pulumi up` that results in an error:

```text
 newrelic:index/nrqlAlertCondition:NrqlAlertCondition resource 'login' has a problem: expected value_function to be one of [single_value sum], got singleValue
```

## Expected behavior

The type hint and the actual expected value need to agree.

## Current behavior

The type hint and the actual expected value do not agree.

## Steps to reproduce

```typescript
const alertCondition = new newrelic.NrqlAlertCondition(
  "test",
  {
    critical: {
      operator: "ABOVE",
      threshold: 0,
      thresholdDuration: 60,
      thresholdOccurrences: "ALL",
    },
    description: "Testing 123",
    // https://github.com/pulumi/pulumi-newrelic/issues/10
    policyId: alertPolicy.id.apply((id) => Number(id)),
    nrql: {
      query:
        `SELECT count(*) FROM SyntheticCheck FACET result ` +
        `WHERE monitorName = 'my-monitor' AND result = 'FAILED'`,
      evaluationOffset: 1,
    },
    runbookUrl: "https://pulumi.com",
    valueFunction: "singleValue",
    violationTimeLimitSeconds: 2592000, // 30 days
  }
);
```

## Context (Environment)

Attempting to create `NrqlAlertCondition`.

**Comment by lblackstone** [comment]
@stack72 Any idea on this one?

**Comment by mjeffryes** [comment]
It doesn't look like `valueFunction` is even a parameter  of `NrqlAlertCondition` on the latest version, so hopefully this is resolved
