### ISSUE TITLE
Refresh fails with many synthetic monitors

### ISSUE THREAD

**Issue by austinbutler** [pulumi/pulumi-newrelic#201]
I have many monitors in a stack and while `pulumi up` and `pulumi preview` work fine, `pulumi refresh` in particular errors with this:

```
 newrelic:synthetics:Monitor (mymonitor):
    error: Preview failed: refreshing urn:pulumi:lol-staging::synthetic-monitors::newrelic:synthetics/monitor:Monitor:mymonitor: GET https:/
/synthetics.newrelic.com/synthetics/api/v4/monitors/uuid_here giving up after 4 attempt(s)
```

I found that using `pulumi refresh --parallel 10` resolved it for me.

Would it make sense to try to back off the parallelism with many monitors or when hitting this error? And is there a way to make the parallel setting persistent?

**Comment by austinbutler** [comment]
Relevant TF issue as well: https://github.com/newrelic/terraform-provider-newrelic/issues/884

**Comment by lukehoban** [comment]
Once there's a fix to the upstream provider we'll pull it in here.

**Comment by austinbutler** [comment]
Seems the relevant upstream issue is now https://github.com/newrelic/terraform-provider-newrelic/issues/1453.

**Comment by stack72** [comment]
Hi folks, when this fix is available in the upstream provider, we will pull it in. I am going to close this out as a duplicate.
