### ISSUE TITLE
Creating a OneDashboard with widgetTables filterCurrentDashboard Always Updates on Pulumi Up

### ISSUE THREAD

**Issue by abrahampcmb** [pulumi/pulumi-newrelic#234]
- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When creating a OneDashboard using the widgetTables filterCurrentDashboard flag set to true then subsequent pulumi up calls always perform an update. Subsequent pulumi up calls should not have any changes, since nothing is being changed.

### Steps to reproduce

1. Create a OneDashboard with a widgetTables widget and the filterCurrentDashboard set to true
2. Perform a pulumi up and see there are changes
3. Repeat step 2 until you get tired ;)

Expected: Step 2 should have no changes.
Actual: There are changes, specifically:
```
    pages      : [
        [0]: {
            widgetTables     : [
                [0]: {
                    filterCurrentDashboard: false => true
                }
            ]
        }
    ]
```

It seems the filterCurrentDashboard bit keeps getting flipped back to false and then needs to be set back to true.

**Comment by tusharshahrs** [comment]
This is due to the following upstream issue:  [filter_current_dashboard of newrelic_one_dashboard is not handled properly](https://github.com/newrelic/terraform-provider-newrelic/issues/1494)

**Comment by AaronFriel** [comment]
Resolved by the upstream last year; all releases this year have included the fix.
