### ISSUE TITLE
NewRelic Alert Workflow Availabilty

### ISSUE THREAD

**Issue by tleung999** [pulumi/pulumi-newrelic#326]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
It looks like Notification Channels are slated to be deprecated.   https://discuss.newrelic.com/t/big-news-for-alerts-and-applied-intelligence/161436.  Is there workflow resource I can use to create workflows through pulumi now?   I wasnt able to find it in the Api docs - https://www.pulumi.com/registry/packages/newrelic/api-docs/notificationchannel/#

### Affected area/feature
I see that Terraform has it available already - https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/workflow

**Comment by stack72** [comment]
Hi @tleung999 

This will be available this week as part of the upgrade to the 3.x series of the Terraform provider. This will be released as part of a major version release of this specific provider

Paul

**Comment by stack72** [comment]
This is available as part of the major version upgrade recently
