### ISSUE TITLE
error: unrecognized resource type (Read): newrelic:synthetics/monitorScript:MonitorScript

### ISSUE THREAD

**Issue by abrahampcmb** [pulumi/pulumi-newrelic#368]
Upgrading pulumi/newrelic library from 4.20.0 to 5.3.0 results in errors when try to access API script synthetic monitors. The following error is received:

error: unrecognized resource type (Read): newrelic:synthetics/monitorScript:MonitorScript

**Comment by AaronFriel** [comment]
Hey @abrahampcmb, thanks for reporting this. Would it be possible for you to write a minimal program to reproduce this?

**Comment by mikhailshilkov** [comment]
Since we haven't heard back and there is no repro program, I'll go ahead and close this issue as stale. Please open a new issue if the problem still persists and provide the details for us to reproduce it. Thank you!
