### ISSUE TITLE
Creating workflow for multiple emails always detects changes to apply

### ISSUE THREAD

**Issue by mariuszniemiec-wl** [pulumi/pulumi-newrelic#551]
### What happened?

I tried to create notification workflow, with use of emails list from configuration (see code below).
However pulumi always see diff in destination IDs array like shown in example below.

Used resources are:
```
newrelic.NotificationDestination
newrelic.NotificationChannel

newrelic.synthetics.CertCheckMonitor
newrelic.synthetics.Monitor

newrelic.AlertPolicy

newrelic.synthetics.AlertCondition

newrelic.Workflow
```

Problem is in diff that creates Workflow resource.

### Example

Following code:

```
const notificationEmails: string[] = config.requireObject<string[]>("notificationEmails")
let destinationIds: any[] = [];

// building destinations IDs from email list:
notificationEmails.map((email: string) => {

  const alertDest = new newrelic.NotificationDestination(`${client}-alertDest-${email}`, {
      name: getNameWithConvention(`Alert ${email}`),
      type: 'EMAIL',
      active: true,
      properties: [
          {
              key: 'email',
              value: email,
          },
      ],
  });

  const alertChannel = new newrelic.NotificationChannel(`${client}-alertChannel-${email}`, {
      name: getNameWithConvention(`Alert channel`),
      destinationId: alertDest.id,
      product: "IINT",
      properties: [
      ],
      type: "EMAIL",
  });
  
  destinationIds.push({
      channelId: alertChannel.id,
  });
})

const alertNotificationWorkflow = new newrelic.Workflow("alertNotificationWorkflow", {
    name: `[${client}] Notification workflow`,
    mutingRulesHandling: "NOTIFY_ALL_ISSUES",
    issuesFilter: {
        name: "Filter-name",
        type: "FILTER",
        predicates: [{
            attribute: "labels.policyIds",
            operator: "EXACTLY_MATCHES",
            values: [
                alertPolicy.id
            ],
        }],
    },
    destinations: destinationIds,
});
```

Pulumi preview, always show (even after up and applying changes):

```
Previewing update (dev):
 Type                        Name                         Plan       Info
 pulumi:pulumi:Stack         pulumi-newrelic-dev             
~   └─ newrelic:index:Workflow  alertNotificationWorkflow    update     [diff: ~destinations]
...
~ destinations: [
  ~ [0]: {
          ~ channelId: "ID1" => "ID2"
        }
  ~ [1]: {
          ~ channelId: "ID2" => "ID1"
        }
]
```

### Output of `pulumi about`

CLI          
Version      3.92.0
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME      VERSION
newrelic  5.15.2
nodejs    unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in nodejs: executable='/bin/node' version='v16.20.2'

Current Stack: organization/pulumi-newrelic-widelab/dev

TYPE                                                            URN
pulumi:pulumi:Stack                                             urn:pulumi:dev::pulumi-newrelic-widelab::pulumi:pulumi:Stack::pulumi-newrelic-widelab-dev
pulumi:providers:newrelic                                       urn:pulumi:dev::pulumi-newrelic-widelab::pulumi:providers:newrelic::default_5_15_2
newrelic:index/notificationDestination:NotificationDestination  urn:pulumi:dev::pulumi-newrelic-widelab::newrelic:index/notificationDestination:NotificationDestination::client-alertDest-mariusz.niemiec@widelab.co
newrelic:synthetics/monitor:Monitor                             urn:pulumi:dev::pulumi-newrelic-widelab::newrelic:synthetics/monitor:Monitor::httpMonitor
newrelic:synthetics/certCheckMonitor:CertCheckMonitor           urn:pulumi:dev::pulumi-newrelic-widelab::newrelic:synthetics/certCheckMonitor:CertCheckMonitor::sslMonitor
newrelic:index/alertPolicy:AlertPolicy                          urn:pulumi:dev::pulumi-newrelic-widelab::newrelic:index/alertPolicy:AlertPolicy::notificationPolicy
newrelic:index/notificationDestination:NotificationDestination  urn:pulumi:dev::pulumi-newrelic-widelab::newrelic:index/notificationDestination:NotificationDestination::client-alertDest-grzegorz.meger@widelab.co
newrelic:index/notificationChannel:NotificationChannel          urn:pulumi:dev::pulumi-newrelic-widelab::newrelic:index/notificationChannel:NotificationChannel::client-alertChannel-mariusz.niemiec@widelab.co
newrelic:synthetics/alertCondition:AlertCondition               urn:pulumi:dev::pulumi-newrelic-widelab::newrelic:synthetics/alertCondition:AlertCondition::sslAlertCondition
newrelic:synthetics/alertCondition:AlertCondition               urn:pulumi:dev::pulumi-newrelic-widelab::newrelic:synthetics/alertCondition:AlertCondition::httpAlertCondition
newrelic:index/notificationChannel:NotificationChannel          urn:pulumi:dev::pulumi-newrelic-widelab::newrelic:index/notificationChannel:NotificationChannel::client-alertChannel-grzegorz.meger@widelab.co
newrelic:index/workflow:Workflow                                urn:pulumi:dev::pulumi-newrelic-widelab::newrelic:index/workflow:Workflow::alertNotificationWorkflow

Found no pending operations associated with dev

Backend        
Name           mario
URL            file://~/Work/pulumi-states/pulumi-newrelic-widelab
User           mario
Organizations  
Token type     personal

Dependencies:
NAME              VERSION
@types/node       16.18.59
@pulumi/newrelic  5.15.2
@pulumi/pulumi    3.92.0

Pulumi locates its logs in /tmp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jodem** [comment]
For posterity I had the same issue with properties of both NotificationDestination and NotificationChannel, a change was always detected. Not sure it helps for the current problem but for those poor fellow loving the satisfying "no change detected" who may end up in the thread with a similar problem.

It turned out it was the bridge adding this extra property every time :

```
{ 
    key: "source",
   label: "terraform-source-internal",
   value: "terraform"
}
```

simply adding it to the property array 1rst position made no more change detected.

**Comment by jodem** [comment]
@estiller  sure, 

As I said it's on the notification destination object I had a change detected all the time until I added an extra property.

`
const teamsNotificationDestination = new newrelic.NotificationDestination(`${args.cluster.id}-teams-notification`, {
                name: `project-${pulumi.getStack()}-${args.cluster.id} ms teams notif dest`,
                active: true,
                properties: [
                    { // I add to add this because it's added by the tf bridge and detected as change every time
                        key: "source",
                        label: "terraform-source-internal",
                        value: "terraform"
                    }, {
                        key: "url",
                        value: args.defaultTeamsWebhookUrl
                    }],
                accountId: args.nrAccountId,
                type: "WEBHOOK"
            }, { provider: newrelicProvider, parent: this });
`

**Comment by iwahbe** [comment]
Hi @mariuszniemiec-wl. Thanks for opening an issue. I suspect that this is a bridge that has to do with set diffs. This might have improved in more modern version of pulumi-cloudflare. Has anyone replicated the issue on a recent version of pulumi-cloudflare?

**Comment by iwahbe** [comment]
@estiller I did mean "pulumi-newrelic". Sorry about that.

Thanks for checking that this still occurs.

**Comment by mariuszniemiec-wl** [comment]
sorry for late answer, I had no time to answer earlier. I confirm issue is stil here, I updated all node package.json including main pulumi as well as pulumi-newrelic.

**Comment by iwahbe** [comment]
Hi @mariuszniemiec-wl. Does the issue still reproduce on [v5.32.1](https://github.com/pulumi/pulumi-newrelic/releases/tag/v5.32.1)? We just released an improvement to this providers diff implementation, and it fixed a similar problem.

**Comment by mariuszniemiec-wl** [comment]
Wonderful and big thanks. This now works as expected. 🎉
