### ISSUE TITLE
Docs or SDK: GcpIntegrations.linkedAccount input resource is a number input but needs to consume  GcpLinkAccount.id which is a string output 

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-newrelic#700]
This issue may be that the example here, https://www.pulumi.com/registry/packages/newrelic/api-docs/cloud/gcpintegrations/
Or the SDK is being generated a bit wonkily.

If nothing else, the (typescript) example needs to have code like this for it to work out of the box.
```
const foo = new newrelic.cloud.GcpLinkAccount("foo", {projectId: "<Your GCP project ID>"});
const foo1 = new newrelic.cloud.GcpIntegrations("foo1", {
    linkedAccountId: foo.id.apply(id => parseInt(id))
})
```

But it seems that either the `GcpLinkAccount.id` output should be a number, or
`GcpIntegrations.linkedAccountId` input should accept a string.
Given that `.id` outputs are generally strings, it seems a more likely solution would be that`.linkedAccountId` should accept a string.

**Comment by mikhailshilkov** [comment]
@iwahbe Could you please comment on the issue to suggest our plan? You marked it as area/docs but it looks like we are trying to change the SDK shape instead.

**Comment by iwahbe** [comment]
When I originally posted the issue, the plan was to fix the docs. We have moved on to addressing the underlying type issue, which should go out next release.
